sudo: required
services:
  - docker

before_install:
  - docker build -t seccomiro/docker-react -f Dockerfile.dev .

script:
  - docker run seccomiro/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: DockerReact-env
  bucket_name: "elasticbeanstalk-us-east-1-034654748293"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_key_id:
    secure: "$AWS_SECRET_KEY"